# ATOM
glm5-fp8-mi355x-atom:
  image: rocm/atom-dev:nightly_202603251629
  model: zai-org/GLM-5-FP8
  model-prefix: glm5
  runner: mi355x
  precision: fp8
  framework: atom
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 8, conc-start: 128, conc-end: 128 }

kimik2.5-fp4-mi355x-atom:
  image: rocm/atom-dev:nightly_202603251629
  model: amd/Kimi-K2.5-MXFP4
  model-prefix: kimik2.5
  runner: mi355x
  precision: fp4
  framework: atom
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 4, conc-start: 64, conc-end: 64 }
    - { tp: 8, conc-start: 64, conc-end: 64 }

minimaxm2.5-fp8-mi355x-atom:
  image: rocm/atom-dev:nightly_202603251629
  model: MiniMaxAI/MiniMax-M2.5
  model-prefix: minimaxm2.5
  runner: mi355x
  precision: fp8
  framework: atom
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 2, conc-start: 64, conc-end: 64 }
    - { tp: 4, conc-start: 64, conc-end: 64 }

gptoss-fp4-mi355x-atom:
  image: rocm/atom-dev:nightly_202603251629
  model: openai/gpt-oss-120b
  model-prefix: gptoss
  runner: mi355x
  precision: fp4
  framework: atom
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 1, conc-start: 128, conc-end: 128 }
    - { tp: 8, conc-start: 128, conc-end: 128 }

dsr1-fp4-mi355x-atom-mtp:
  image: rocm/atom:rocm7.2.1-ubuntu24.04-pytorch2.9.1-atom0.1.2
  model: amd/DeepSeek-R1-0528-MXFP4-MTP-MoEFP4
  model-prefix: dsr1
  runner: mi355x
  precision: fp4
  framework: atom
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 4, conc-start: 256, conc-end: 256, spec-decoding: mtp }
    - { tp: 8, conc-start: 256, conc-end: 256, spec-decoding: mtp }

dsr1-fp8-mi355x-atom-mtp:
  image: rocm/atom:rocm7.2.1-ubuntu24.04-pytorch2.9.1-atom0.1.2
  model: deepseek-ai/DeepSeek-R1-0528
  model-prefix: dsr1
  runner: mi355x
  precision: fp8
  framework: atom
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 8, conc-start: 256, conc-end: 256, spec-decoding: mtp }

# VLLM
kimik2.5-fp4-mi355x-vllm:
  image: vllm/vllm-openai-rocm:v0.18.0
  model: amd/Kimi-K2.5-MXFP4
  model-prefix: kimik2.5
  runner: mi355x
  precision: fp4
  framework: vllm
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 4, conc-start: 64, conc-end: 64 }
    - { tp: 8, conc-start: 64, conc-end: 64 }

kimik2.5-int4-mi355x-vllm:
  image: vllm/vllm-openai-rocm:v0.18.0
  model: moonshotai/Kimi-K2.5
  model-prefix: kimik2.5
  runner: mi355x
  precision: int4
  framework: vllm
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 4, conc-start: 64, conc-end: 64 }
    - { tp: 8, conc-start: 64, conc-end: 64 }