# VLLM/SGL
dsv4-fp8-mi355x-sglang:
  image: rocm/sgl-dev:rocm720-deepseek-v4-mi35x
  model: sgl-project/DeepSeek-V4-Pro-FP8
  model-prefix: dsv4
  runner: mi355x
  precision: fp8
  framework: sglang
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }

dsv4-fp4-mi355x-sglang:
  image: rocm/sgl-dev:rocm720-deepseek-v4-mi35x
  model: deepseek-ai/DeepSeek-V4-Pro
  model-prefix: dsv4
  runner: mi355x
  precision: fp4
  framework: sglang
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 32 }
  #- isl: 8192
  #  osl: 1024
  #  search-space:
  #  - { tp: 8, conc-start: 4, conc-end: 64 }

dsv4-fp4-mi355x-vllm:
  #image: rocm/vllm-dev:deepseek-v4-latest
  image: vllm/vllm-openai-rocm:nightly
  model: deepseek-ai/DeepSeek-V4-Pro
  model-prefix: dsv4
  runner: mi355x
  precision: fp4
  framework: vllm
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 32 }

dsv4-fp4-mi355x-atom:
  image: rocm/atom-dev:nightly_202605071039
  model: deepseek-ai/DeepSeek-V4-Pro
  model-prefix: dsv4
  runner: mi355x
  precision: fp4
  framework: atom
  multinode: false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 256 }