kimik3-fp4-mi355x-vllm-agentic-mtp:
  image: vllm/vllm-openai-rocm:nightly-e7edf17cea217e52701f913cd8491fcacf2d9490
  model: moonshotai/Kimi-K3
  model-prefix: kimik3
  runner: cluster:mi355x-amds
  precision: fp4
  framework: vllm
  multinode: false
  scenarios:
    agentic-coding:
    - dram-utilization: 0.65
      search-space:
      - { tp: 8, ep: 1, dcp-size: 1, kv-offloading: none, conc-list: [1, 4, 8], spec-decoding: mtp }
      - { tp: 8, ep: 1, dcp-size: 8, kv-offloading: dram, kv-offload-backend: { name: vllm-simple }, conc-list: [16, 32, 64, 70, 72, 74, 80], spec-decoding: mtp }

glm5.2-fp4-mi355x-sglang-agentic-mtp:
  image: lmsysorg/sglang-rocm:v0.5.19-rocm720-mi35x-20260909
  model: amd/GLM-5.2-MXFP4
  model-prefix: glm5.2
  runner: cluster:mi355x-amds-2
  precision: fp4
  framework: sglang
  multinode: false
  scenarios:
    agentic-coding:
    - dram-utilization: 0.8
      search-space:
      # - { tp: 4, ep: 4, kv-offloading: dram, kv-offload-backend: { name: hicache }, conc-list: [1, 2, 4, 8, 10, 12], spec-decoding: mtp }
      - { tp: 8, ep: 8, kv-offloading: dram, kv-offload-backend: { name: hicache }, conc-list: [16] }
