labels:
  cluster:mi355x-amds:
    - mi355x-amd_m15_17_ajith
hardware:
  cluster:mi300x-tw:
    available-cpu-dram-mib: 2_322_328
    gpus-per-node: 8
  cluster:mi325x-amds:
    available-cpu-dram-mib: 3_091_589
    gpus-per-node: 8
  cluster:mi325x-tw:
    available-cpu-dram-mib: 3_095_792
    gpus-per-node: 8
  cluster:mi355x-amds:
    available-cpu-dram-mib: 3_095_781
    gpus-per-node: 8
