name: Atom docker CI
run-name: Atom docker node CI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  atom-ci:
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit
    with:
      generate-cli-command: "test-config --config-files .github/configs/amd-master.yaml --config-keys '*-atom-*docker-ci'"
      test-name: atom-ci
