name: Template - Collect Results

on:
  workflow_call:
    inputs:
      exp-name:
        required: true
        type: string

jobs:
  collect-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: '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'
          fetch-depth: 0

      - name: Download JSON artifacts
        uses: actions/download-artifact@v4
        with:
          path: results/
          pattern: ${{ inputs.exp-name }}_*

      - name: Print summary
        run: python3 utils/summarize.py results/ ${{ inputs.exp-name }} >> $GITHUB_STEP_SUMMARY

      - name: Aggregate results
        run: python3 utils/collect_results.py results/ ${{ inputs.exp-name }}

