name: Test - DeepSeek R1 sweep, MI355X/B200, best vs best, 0927 (bd781f) rc1 image 

on:
  workflow_dispatch:
    inputs:
      run_1k1k:
        type: boolean
        required: false
      run_8k1k:
        type: boolean
        required: false
      run_1k8k:
        type: boolean
        required: false

      use_b200:
        type: boolean
        required: true
      use_mi355x:
        type: boolean
        required: false

jobs:
  ds-r1-test-run:
    uses: ./.github/workflows/dsr1-sweep-tmpl.yml
    secrets: inherit
    with:
      run_1k1k: ${{ inputs.run_1k1k }}
      run_8k1k: ${{ inputs.run_8k1k }}
      run_1k8k: ${{ inputs.run_1k8k }}
      use_b200: ${{ inputs.use_b200 }}
      use_mi355x: ${{ inputs.use_mi355x }}
