name: Test - DeepSeek R1, SGLang on MI355 (accuracy)

on:
  workflow_dispatch:
    inputs:
      run_accuracy:
        type: boolean
        required: true

      use_mi300x:
        type: boolean
        required: true
      use_mi325x:
        type: boolean
        required: true
      use_mi355x:
        type: boolean
        required: true

jobs:
  dsr1-accuracy:
    if: ${{ inputs.run_accuracy }}
    uses: ./.github/workflows/dsr1-sgl-accuracy-tmpl.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_accuracy'
      use_mi300x: ${{ inputs.use_mi300x }}
      use_mi325x: ${{ inputs.use_mi325x }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-dsr1-accuracy-results:
    needs: dsr1-accuracy
    if: ${{ inputs.run_accuracy && always() }}
    uses: ./.github/workflows/collect-accuracy-results.yml
    secrets: inherit
    with:
      exp-name: 'dsr1_accuracy'

