name: Full Sweep Scheduler - 1k8k

on:
  workflow_dispatch:
    schedule:
      - cron: "27 8 * * *"

jobs:
  mega-run:
    if: ${{ inputs.testcase == 'perf' }}
    uses: ./.github/workflows/full-sweep-tmpl.yml
    secrets: inherit
    with:
      ref: atom
      run_1k1k: true
      run_8k1k: false
      run_1k8k: false
      run_dsr1: true
      run_gptoss: true
      use_mi355x: true
      atom_image: "rocm/atom:latest"