name: Full Sweep Scheduler - 1k1k

on:
  workflow_dispatch:

jobs:
  mega-run:
    uses: ./.github/workflows/full-sweep-tmpl.yml
    secrets: inherit
    with:
      run_1k1k: true
      run_8k1k: false
      run_1k8k: false
      run_dsr1: true
      run_gptoss: true
      use_mi355x: true
      atom_image: "rocm/atom:latest"