name: Full Sweep Scheduler - 8k1k

on:
  workflow_dispatch:
    inputs:
      run_dsr1:
        required: true
        type: boolean
        default: False
      run_gptoss:
        required: true
        type: boolean
        default: False

jobs:
  mega-run-dsr1:
    if: ${{ inputs.run_dsr1 }}
    uses: ./.github/workflows/full-sweep-tmpl_dsr1.yml
    secrets: inherit
    with:
      run_1k1k: false
      run_8k1k: true
      run_1k8k: false
      use_h100: false
      use_h200: false
      use_b200: true
      use_mi300x: false
      use_mi325x: false
      use_mi355x: false
      use_gb200: false

  mega-run-gptoss:
    if: ${{ inputs.run_gptoss }}
    uses: ./.github/workflows/full-sweep-tmpl_gptoss.yml
    secrets: inherit
    with:
      run_1k1k: false
      run_8k1k: true
      run_1k8k: false
      use_h100: false
      use_h200: false
      use_b200: true
      use_mi300x: false
      use_mi325x: false
      use_mi355x: false
      use_gb200: false
