name: Test - GPT OSS sweep, MI355X, 1002 (bd781f) image quick reduce applied 

on:
  workflow_dispatch:
    inputs:
      run_1k1k:
        type: boolean
        required: false
        default: false
      run_8k1k:
        type: boolean
        required: false
        default: false
      run_1k8k:
        type: boolean
        required: false
        default: false
      run_acc:
        type: boolean
        required: false
        default: false
      use_mi355x:
        type: boolean
        required: false

jobs:
  gpt-oss-test-run:
    uses: ./.github/workflows/gpt-oss-sweep-tmpl_quick_reduce.yml
    secrets: inherit
    with:
      run_1k1k: ${{ inputs.run_1k1k }}
      run_8k1k: ${{ inputs.run_8k1k }}
      run_1k8k: ${{ inputs.run_1k8k }}
      run_acc: ${{ inputs.run_acc }}
      use_mi355x: ${{ inputs.use_mi355x }}
