name: Template - Full Sweep

on:
  workflow_call:
    inputs:
      run_1k1k:
        type: boolean
        required: false
        default: false
      run_8k1k:
        type: boolean
        required: false
        default: false
      run_1k8k:
        type: boolean
        required: false
        default: false
      run_acc:
        type: boolean
        required: false
        default: false
      collect-acc-results:
        type: boolean
        required: false
        default: false
      use_b200:
        type: boolean
        required: false
      use_mi355x:
        type: boolean
        required: true

jobs:
  gptoss-acc:
    if: ${{ inputs.run_acc }}
    uses: ./.github/workflows/gptoss-tmpl_quick_reduce.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_acc'
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      use_b200: ${{ inputs.use_b200 }}
      use_mi355x: ${{ inputs.use_mi355x }}
      run-accuracy-test: true
      run-benchmark: false

  collect-gptoss-acc-results:
    needs: gptoss-acc
    if: ${{ inputs.collect-acc-results && inputs.run_acc && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_acc'

  gptoss-1k1k:
    if: ${{ inputs.run_1k1k }}
    uses: ./.github/workflows/gptoss-tmpl_quick_reduce.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_1k1k'
      isl: 1024
      osl: 1024
      max-model-len: 2048
      random-range-ratio: 0.8
      use_b200: ${{ inputs.use_b200 }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-gptoss-1k1k-results:
    needs: gptoss-1k1k
    if: ${{ inputs.run_1k1k && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_1k1k'

  gptoss-8k1k:
    if: ${{ inputs.run_8k1k }}
    uses: ./.github/workflows/gptoss-tmpl_quick_reduce.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_8k1k'
      isl: 8192
      osl: 1024
      max-model-len: 9216
      random-range-ratio: 0.8
      use_b200: ${{ inputs.use_b200 }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-gptoss-8k1k-results:
    needs: gptoss-8k1k
    if: ${{ inputs.run_8k1k && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_8k1k'

  gptoss-1k8k:
    if: ${{ inputs.run_1k8k }}
    uses: ./.github/workflows/gptoss-tmpl_quick_reduce.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_1k8k'
      isl: 1024
      osl: 8192
      max-model-len: 9216
      random-range-ratio: 0.8
      use_b200: ${{ inputs.use_b200 }}
      use_mi355x: ${{ inputs.use_mi355x }}

  collect-gptoss-1k8k-results:
    needs: gptoss-1k8k
    if: ${{ inputs.run_1k8k && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_1k8k'
