name: Template - gpt-oss

on:
  workflow_call:
    inputs:
      exp-name:
        required: true
        type: string
      isl:
        required: true
        type: string
      osl:
        required: true
        type: string
      max-model-len:
        required: true
        type: string
      random-range-ratio:
        required: true
        type: string

      use_b200:
        type: boolean
        required: false
      use_mi355x:
        type: boolean
        required: true

jobs:
  bmk-b200:
    if: ${{ inputs.use_b200 }}
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: shaderform-10
      image: 'vllm/vllm-openai:v0.10.2'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2, 4, 8]'
      framework: 'vllm'
      precision: 'fp4'

  bmk-b200-trt:
    if: ${{ inputs.use_b200 }}
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: shaderform-10
      image: 'nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2.post2'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2, 4, 8]'
      framework: 'trt'
      precision: 'fp4'

  bmk-mi355x:
    if: ${{ inputs.use_mi355x }}
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: m10-33
      image: 'rocm/pytorch-private:rocm7.0_vllm0.10.1_instinct_20250927_rc1_quick_reduce_update'
      model: 'openai/gpt-oss-120b'
      tp-list: '[8]'
      framework: 'vllm'
      precision: 'fp4'
