name: Template - gpt-oss

on:
  workflow_call:
    inputs:
      exp-name:
        required: true
        type: string
      isl:
        required: true
        type: string
      osl:
        required: true
        type: string
      max-model-len:
        required: true
        type: string
      random-range-ratio:
        required: true
        type: string

      use_mi355x:
        type: boolean
        required: true

jobs:
  bmk-mi355x:
    if: ${{ inputs.use_mi355x }}
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: [self-hosted, mi355x-amd]
      image: 'rocm/pytorch-private:vllm_85_rocm7.0_aiter_0927_bd781f_latest_rccl'
      model: 'openai/gpt-oss-120b'
      tp-list: '[8]'
      framework: 'vllm'
      precision: 'fp4'
