name: Hello Cron

on:
    schedule:
        - cron: "15 2 * * *"
    workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Print hello
              run: echo "hello"
