name: Run benchmark workflow
on: [push] # Or any other event that triggers this workflow
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/shaderform-10-b200_test.yml
    with:
      exp-name: 'gptoss_trtllm'
      isl: '1024'
      osl: '1024'
      max-model-len: '2048'
      random-range-ratio: '0.8'
      use_b200: true
      runner_label: 'self-hosted'