name: Run benchmark workflow
on: [push] # Or any other event that triggers this workflow
  workflow_call:
    inputs:
      run_1k1k:
        type: boolean
        required: true
      run_8k1k:
        type: boolean
        required: true
      run_1k8k:
        type: boolean
        required: true
      use_b200:
        type: boolean
        required: true
        default: true
jobs:
  gptoss-1k1k:
    uses: ./.github/workflows/shaderform-10-b200_test.yml
    with:
      exp-name: 'gptoss_trtllm'
      isl: '1024'
      osl: '1024'
      max-model-len: '2048'
      random-range-ratio: '0.8'
      use_b200: true
      runner_label: 'self-hosted'
  collect-gptoss-1k1k-results:
    needs: gptoss-1k1k
    if: ${{ inputs.run_1k1k && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_1k1k'

  gptoss-8k1k:
    uses: ./.github/workflows/shaderform-10-b200_test.yml
    with:
      exp-name: 'gptoss_trtllm'
      isl: '8292'
      osl: '1024'
      max-model-len: '9216'
      random-range-ratio: '0.8'
      use_b200: true
      runner_label: 'self-hosted'
  collect-gptoss-8k1k-results:
    needs: gptoss-8k1k
    if: ${{ inputs.run_8k1k && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_8k1k'

  gptoss-1k8k:
    uses: ./.github/workflows/shaderform-10-b200_test.yml
    with:
      exp-name: 'gptoss_trtllm'
      isl: '1024'
      osl: '8192'
      max-model-len: '9216'
      random-range-ratio: '0.8'
      use_b200: true
      runner_label: 'self-hosted'
  collect-gptoss-1k8k-results:
    needs: gptoss-1k8k
    if: ${{ inputs.run_1k8k && (success() || failure()) }}
    uses: ./.github/workflows/collect-results.yml
    secrets: inherit
    with:
      exp-name: 'gptoss_1k8k'