name: GPT OSS 120B SWEEP TRTLLM B200
on: [push] # Or any other event that triggers this workflow
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/shaderform-10-b200_test.yml
    with:
      runner_label: 'self-hosted'